baseURL = ''
languageCode = 'en-us'
title = 'Your Name'
theme = "hugo-academicpages"

[[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 10

[[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 20

[[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 30

[[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 40

[[menu.main]]
    identifier = "blog"
    name = "Blog Posts"
    url = "/blog/"
    weight = 50

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/cv/"
  weight = 50

[[menu.main]]
  identifier = "guide"
  name = "Guide"
  url = "/guide/"
  weight = 50


[params]
  follow_label = "Follow"
  powered_by = "Powered by"

  [params.author]
    name = "Your Sidebar Name"
    avatar = "https://academicpages.github.io/images/profile.png"
    bio = "Your biography for the left-hand sidebar"
    [params.author.details]
      [[params.author.details.list]]
      class = "location"
      icon = "fa-map-marker"
      title = "Location"

    [params.author.contact]
      [[params.author.contact.list]]
      class = "email"
      icon = "fa-envelope"
      url = "mailto:youremail@yourcompany.com"
      title = "Email"

    [params.author.social]
      [[params.author.social.list]]
      class = "googelscholar"
      icon = "fas fa-graduation-cap"
      url = "#"
      title = "Google Scholar"

      [[params.author.social.list]]
      class = "linkedin"
      icon = "fab fa-linkedin"
      url = "//linkedin.com/in/sinjoysaha"
      title = "LinkedIn"

      [[params.author.social.list]]
      class = "twitter"
      icon = "fab fa-twitter-square"
      url = "//twitter.com/sinjoysaha"
      title = "Twitter"

      [[params.author.social.list]]
      class = "github"
      icon = "fab fa-github"
      url = "//github.com/sinjoysaha/hugo-academicpages"
      title = "GitHub"

    
      
